name: DockerImageBuilder
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - antlr-python-runtime=4.9.3
  - anyconfig=0.14.0
  - bcrypt=4.2.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - certifi=2024.7.4
  - cffi=1.17.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - colorama=0.4.6
  - cryptography=43.0.0
  - docker-py=7.1.0
  - dockerfile-parse=2.0.1
  - docstring_parser=0.16
  - dotdict=0.1
  - flatten-dict=0.4.2
  - frozendict=2.4.4
  - h2=4.1.0
  - hpack=4.0.0
  - hyperframe=6.0.1
  - idna=3.7
  - jinja2=3.1.4
  - ld_impl_linux-64=2.40
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.6.2
  - libffi=3.4.2
  - libgcc-ng=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libgomp=14.1.0
  - liblapack=3.9.0
  - libnsl=2.0.1
  - libopenblas=0.3.27
  - libsodium=1.0.18
  - libsqlite=3.46.0
  - libstdcxx-ng=14.1.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - markdown-it-py=3.0.0
  - markupsafe=2.1.5
  - mdurl=0.1.2
  - ncurses=6.5
  - numpy=2.1.0
  - omegaconf=2.3.0
  - openssl=3.3.1
  - pandas=2.2.2
  - paramiko=3.4.1
  - pathlib2=2.3.7.post1
  - pathspec=0.12.1
  - pip=24.2
  - pycparser=2.22
  - pygments=2.18.0
  - pynacl=1.5.0
  - pysocks=1.7.1
  - python=3.12.5
  - python-dateutil=2.9.0
  - python-dotenv=1.0.1
  - python-tzdata=2024.1
  - python_abi=3.12
  - pytz=2024.1
  - pywin32-on-windows=0.1.0
  - pyyaml=6.0.2
  - readline=8.2
  - requests=2.32.3
  - rich=13.7.1
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - schema=0.7.7
  - setuptools=72.2.0
  - shtab=1.7.1
  - six=1.16.0
  - tk=8.6.13
  - toml=0.10.2
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tyro=0.8.8
  - tzdata=2024a
  - urllib3=2.2.2
  - validobj=1.1
  - websocket-client=1.8.0
  - wheel=0.44.0
  - xz=5.2.6
  - yaml=0.2.5
  - yamllint=1.35.1
  - zstandard=0.23.0
  - zstd=1.5.6
